/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DayswappersInterface extends ethers.utils.Interface {
  functions: {
    "payToIntroducer(address,uint256[3])": FunctionFragment;
    "payToTree(address,uint256[3])": FunctionFragment;
    "reportVolume(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "payToIntroducer",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "payToTree",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "reportVolume",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "payToIntroducer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payToTree", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportVolume",
    data: BytesLike
  ): Result;

  events: {};
}

export class Dayswappers extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DayswappersInterface;

  functions: {
    payToIntroducer(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "payToIntroducer(address,uint256[3])"(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    payToTree(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "payToTree(address,uint256[3])"(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    reportVolume(
      _networker: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "reportVolume(address,uint256)"(
      _networker: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  payToIntroducer(
    _networker: string,
    _rewardRatio: BigNumberish[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "payToIntroducer(address,uint256[3])"(
    _networker: string,
    _rewardRatio: BigNumberish[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  payToTree(
    _networker: string,
    _rewardRatio: BigNumberish[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "payToTree(address,uint256[3])"(
    _networker: string,
    _rewardRatio: BigNumberish[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  reportVolume(
    _networker: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "reportVolume(address,uint256)"(
    _networker: string,
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    payToIntroducer(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "payToIntroducer(address,uint256[3])"(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    payToTree(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "payToTree(address,uint256[3])"(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    reportVolume(
      _networker: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "reportVolume(address,uint256)"(
      _networker: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    payToIntroducer(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "payToIntroducer(address,uint256[3])"(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    payToTree(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "payToTree(address,uint256[3])"(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    reportVolume(
      _networker: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "reportVolume(address,uint256)"(
      _networker: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    payToIntroducer(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "payToIntroducer(address,uint256[3])"(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    payToTree(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "payToTree(address,uint256[3])"(
      _networker: string,
      _rewardRatio: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    reportVolume(
      _networker: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "reportVolume(address,uint256)"(
      _networker: string,
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
