/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IRentingDappManagerInterface extends ethers.utils.Interface {
  functions: {
    "payRewards(address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "payRewards",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "payRewards", data: BytesLike): Result;

  events: {};
}

export class IRentingDappManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IRentingDappManagerInterface;

  functions: {
    payRewards(
      _networker: string,
      _treeAmount: BigNumberish,
      _introducerAmount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "payRewards(address,uint256,uint256)"(
      _networker: string,
      _treeAmount: BigNumberish,
      _introducerAmount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  payRewards(
    _networker: string,
    _treeAmount: BigNumberish,
    _introducerAmount: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "payRewards(address,uint256,uint256)"(
    _networker: string,
    _treeAmount: BigNumberish,
    _introducerAmount: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    payRewards(
      _networker: string,
      _treeAmount: BigNumberish,
      _introducerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "payRewards(address,uint256,uint256)"(
      _networker: string,
      _treeAmount: BigNumberish,
      _introducerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    payRewards(
      _networker: string,
      _treeAmount: BigNumberish,
      _introducerAmount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "payRewards(address,uint256,uint256)"(
      _networker: string,
      _treeAmount: BigNumberish,
      _introducerAmount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    payRewards(
      _networker: string,
      _treeAmount: BigNumberish,
      _introducerAmount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "payRewards(address,uint256,uint256)"(
      _networker: string,
      _treeAmount: BigNumberish,
      _introducerAmount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
