//Images
const path = {
    cardProduct: require("../../assets/Images/itemOne.jpg"),
    boxDesc: require("../../assets/Images/boxDesc.png"),
    centralWhite: require("../../assets/Images/centralWhite.png"),
    transWhite: require("../../assets/Images/transWhite.png"),
    rentWhite: require("../../assets/Images/rentWhite.png"),
    rentingdapp: require("../../assets/Images/rentingdapp.png"),
    realEstate: require("../../assets/Images/realEstate.jpg"),
    bike: require("../../assets/Images/bike.jpg"),
    furniture: require("../../assets/Images/furniture.jpg"),
    Vehicle: require("../../assets/Images/Vehicle.jpg"),
    mobile: require("../../assets/Images/mobile.jpg"),
    itemOne: require("../../assets/Images/itemOne.jpg"),
    itemTwo: require("../../assets/Images/itemTwo.jpg"),
    rentcolor: require("../../assets/Images/rentcolor.png"),
    colorTransfer: require("../../assets/Images/colorTransfer.png"),
    Cart: require("../../assets/Images/Cart.png"),
    logocolor: require("../../assets/Images/logocolor.png"),
    orangeStar:require("../../assets/Images/orangeStar.png"),
    rlOne:require("../../assets/Images/rlone.jpg"),
    rlTwo:require("../../assets/Images/rltwo.jpg"),
    rlThree:require("../../assets/Images/rlthree.jpg"),
    rlFour:require("../../assets/Images/rlfour.jpg"),
    EmptyChat:require("../../assets/Images/EmptyChat.png"),
    fileUpload: require("../../assets/Images/fileUpload.png"),
    comingsoon: require("../../assets/Images/comingSoon.png"),
    defaultProfile: require("../../assets/Images/defaultProfile.jpeg"),
    noPreview:require("../../assets/Images/noPreview.png"),

    //Icons
    profilewhite: require("../../assets/Icons/profilewhite.png"),
    Nortificationwhite: require("../../assets/Icons/Nortificationwhite.png"),
    Chatwhite: require("../../assets/Icons/Chatwhite.png"),
    whitecart: require("../../assets/Icons/whitecart.png"),
    ChatGrey: require("../../assets/Icons/ChatGrey.png"),
    cartgrey: require("../../assets/Icons/cartgrey.png"),
    Notifactiongrey: require("../../assets/Icons/Notifactiongrey.png"),
    Prfilegrey: require("../../assets/Icons/Prfilegrey.png"),
    orangeArrow: require("../../assets/Icons/orangeArrow.png"),
    imgprf2: require("../../assets/Icons/imgprf2.jpg"),
    imgProfile: require("../../assets/Icons/imgProfile.jpg"),
    manOne: require("../../assets/Icons/manOne.jpg"),
    manTwo: require("../../assets/Icons/manTwo.jpg"),
    facebook: require("../../assets/Icons/facebook.png"),
    instagram: require("../../assets/Icons/instagram.png"),
    twitter: require("../../assets/Icons/twitter.png"),
    youtube: require("../../assets/Icons/youtube.png"),
    noPreview: require("../../assets/Images/no-preview.jpg"),

};
export default {
    path
}
